--- 
- hosts: localhost
  become: true
  vars:
    cont_name: "{{cname}}"
  
  tasks:
  - name: Install pip
    apt: 
      name: python-pip 
      state: present
      force_apt_get: yes
  
  - name: Dependencies
    pip:
      name: docker

  - name: Build an image and push it to a private repo
    docker_image:
      build:
        path: ./
        pull: no
      name: silverimage
      tag: latest
      source: build
  
  - name: Create container
    docker_container:
      name: "{{cont_name}}"
      image: silverimage
      purge_networks: yes
      privileged: yes
      detach: yes
      interactive: yes
