---
- hosts: localhost
  gather_facts: false
  become: true

  tasks:
  - name: Add veth pairs
    command: "{{item}}"
    with_items:
      - ip link add {{c1name}}_q2br1 type veth peer name q2br1_{{c1name}}
      - ip link add {{c2name}}_q2br3 type veth peer name q2br3_{{c2name}}
  
  - name: Get PID of container1
    docker_container_info:
      name: '{{c1name}}'
    register: result

  - set_fact:
      c1_id: '{{result.container.State.Pid}}'

  - name: Get PID of container2
    docker_container_info:
      name: '{{c2name}}'
    register: result
  
  - set_fact:
      c2_id: '{{result.container.State.Pid}}'
  
  - name: Attach veth pairs to containers
    command: "{{item}}"
    with_items:
      - ip link set netns {{c1_id}} dev {{c1name}}_q2br1
      - ip link set netns {{c2_id}} dev {{c2name}}_q2br3

  - name: Add veth pairs to namespaces
    command: "{{item}}"
    with_items:
      - ip link set netns q2ns1 dev q2br1_{{c1name}}
      - ip link set netns q2ns2 dev q2br3_{{c2name}}

  - name: Attach veth pair to bridges
    command: "{{item}}"
    with_items:
      - ip netns exec q2ns1 brctl addif q2br1 q2br1_{{c1name}}
      - ip netns exec q2ns2 brctl addif q2br3 q2br3_{{c2name}}

  - name: Up the interfaces
    command: "{{item}}"
    with_items:
      - ip netns exec q2ns1 ip link set dev q2br1_{{c1name}} up
      - ip netns exec q2ns2 ip link set dev q2br3_{{c2name}} up
      - docker exec {{c1name}} ip link set dev {{c1name}}_q2br1 up
      - docker exec {{c2name}} ip link set dev {{c2name}}_q2br3 up

  - name: Assign IP address
    command: "{{item}}"
    with_items:
      - docker exec {{c1name}} ip addr add 111.0.0.6/24 dev {{c1name}}_q2br1
      - docker exec {{c2name}} ip addr add 111.0.0.7/24 dev {{c2name}}_q2br3   