FROM ubuntu
RUN apt-get update && apt-get -y install \
        iputils-ping \
        iproute2 \
        net-tools \
        tcpdump \
        iperf3 \
        sudo \
        traceroute \
        isc-dhcp-client \
        ifenslave \
        iptables
