--- 
- hosts: localhost
  become: true
  
  tasks:
  - name: Dependencies
    pip:
      name: docker

  - name: Build an image and push it to a private repo
    docker_image:
      build:
        path: ./
        pull: no
      name: silverimage
      tag: latest
      source: build